// Turns a per-entity record map into a paste-ready Questie "Forever...Fixes"
// corrections module - a `QuestieLoader` module exposing a single `:Load()`
// function that returns a sparse map of entityId -> { [entityKeys.field] = value }.
//
// Unlike a full DB dump, this only ever emits fields we actually have an
// aggregated Fact for (see emit/npc.ts); entities with no corrected fields are
// omitted entirely, and fields with no observer/no data are never defaulted.
// This matches how Questie's own `Database/Custom/Fixes/foreverNPCFixes.lua`
// (etc.) is structured: a set of overrides layered on top of the base DB, not
// a replacement for it.

export interface CorrectionsWriterHeader {
  sourceFileNames: string[];
  sessionCount: number;
  generatedAt: Date;
}

/** Renders an object key as a Lua table constructor key, e.g. `["creatures"]` or `[7]`. */
function luaKey(key: string): string {
  return /^\d+$/.test(key) ? `[${key}]` : `[${luaValue(key)}]`;
}

/** Checks if value is a startedBy/finishedBy-like object with positional arrays. */
function isStarterTypeTable(
  value: unknown,
): value is { creatures?: number[]; objects?: number[]; items?: number[] } {
  if (typeof value !== "object" || value === null || Array.isArray(value)) return false;
  const keys = Object.keys(value);
  // Known starter types for startedBy/finishedBy
  return keys.every((k) => ["creatures", "objects", "items"].includes(k));
}

function luaValue(value: unknown): string {
  if (value === null || value === undefined) {
    return "nil";
  }
  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "nil";
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "string") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  if (Array.isArray(value)) {
    return value.length === 0 ? "nil" : `{${value.map(luaValue).join(",")}}`;
  }
  if (typeof value === "object") {
    // Special case: startedBy/finishedBy use positional tables
    // { creatures: [...], objects: [...], items: [...] } → {{...},{...},{...}}
    // Omit trailing empty arrays (render as nil) to match Questie convention
    if (isStarterTypeTable(value)) {
      const pos = [value.creatures ?? [], value.objects ?? [], value.items ?? []];
      // Omit trailing empty arrays
      while (pos.length > 0 && pos[pos.length - 1].length === 0) {
        pos.pop();
      }
      if (pos.length === 0) return "nil";
      return `{${pos.map(luaValue).join(",")}}`;
    }
    const entries = Object.entries(value as Record<string, unknown>);
    return `{${entries.map(([key, entryValue]) => `${luaKey(key)}=${luaValue(entryValue)}`).join(",")}}`;
  }
  throw new Error(`luaValue: unsupported value type ${typeof value} (${JSON.stringify(value)})`);
}

/**
 * @param moduleName e.g. "ForeverTraceNpcFixes" - becomes the QuestieLoader module name.
 * @param keysLocalName e.g. "npcKeys" - the `QuestieDB.<keysLocalName>` field-key table used
 *   to translate each record's field names into their real Questie key lookups.
 * @param records entityId -> only the fields that were actually extracted (already sparse,
 *   see emit/npc.ts); entities with an empty record are skipped.
 */
export function writeQuestieCorrectionsLua(
  moduleName: string,
  keysLocalName: string,
  records: Map<number, Record<string, unknown>>,
  header: CorrectionsWriterHeader,
): string {
  const lines: string[] = [
    `---@class ${moduleName}`,
    `local ${moduleName} = QuestieLoader:CreateModule("${moduleName}")`,
    "",
    "---@type QuestieDB",
    'local QuestieDB = QuestieLoader:ImportModule("QuestieDB")',
    "",
    "-- Generated by QuestieTrace extract (tools/trace-analyzer)",
    `-- Source trace files: ${header.sourceFileNames.length}`,
    `-- Sessions aggregated: ${header.sessionCount}`,
    `-- Generated at: ${header.generatedAt.toISOString()}`,
    `function ${moduleName}:Load()`,
    `    local ${keysLocalName} = QuestieDB.${keysLocalName}`,
    "",
    "    return {",
  ];

  const sortedIds = [...records.keys()].sort((a, b) => a - b);
  for (const id of sortedIds) {
    const record = records.get(id);
    const fieldNames = record ? Object.keys(record) : [];
    if (fieldNames.length === 0) continue;

    lines.push(`        [${id}] = {`);
    for (const fieldName of fieldNames) {
      lines.push(`            [${keysLocalName}.${fieldName}] = ${luaValue(record![fieldName])},`);
    }
    lines.push("        },");
  }

  lines.push("    }");
  lines.push("end");

  return lines.join("\n");
}
