// Turns a per-entity record map into a paste-ready Questie-format Lua file.
//
// Walks the *schema* (not the extracted data) to build each row, filling any
// field the caller didn't set with its declared schema default. This is what
// guarantees "every emitted row has every field populated" as a property of
// the writer, not something every emit/*.ts has to remember.

import type { QuestieEntitySchema } from "./questie-keys";

export interface LuaWriterHeader {
  sourceFileName: string;
  sessionCount: number;
  generatedAt: Date;
}

function luaValue(value: unknown): string {
  if (value === null || value === undefined) {
    return "nil";
  }
  if (typeof value === "number") {
    return Number.isFinite(value) ? String(value) : "nil";
  }
  if (typeof value === "boolean") {
    return value ? "true" : "false";
  }
  if (typeof value === "string") {
    return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
  }
  throw new Error(`luaValue: unsupported value type ${typeof value} (${JSON.stringify(value)})`);
}

/**
 * @param luaVariableName e.g. "npcData"
 * @param schema the entity's `*Keys` schema (index + default per field)
 * @param records entityId -> named record with only the fields that were actually extracted set
 */
export function writeQuestieLua(
  luaVariableName: string,
  schema: QuestieEntitySchema,
  records: Map<number, Record<string, unknown>>,
  header: LuaWriterHeader,
): string {
  const fieldEntries = Object.entries(schema);
  const maxIndex = fieldEntries.reduce((max, [, field]) => Math.max(max, field.index), 0);

  const lines: string[] = [
    "-- Generated by QuestieTrace extract (tools/trace-analyzer)",
    `-- Source trace file: ${header.sourceFileName}`,
    `-- Sessions aggregated: ${header.sessionCount}`,
    `-- Generated at: ${header.generatedAt.toISOString()}`,
    `local ${luaVariableName} = {`,
  ];

  const sortedIds = [...records.keys()].sort((a, b) => a - b);
  for (const id of sortedIds) {
    const record = records.get(id) ?? {};
    const positional: unknown[] = new Array(maxIndex).fill(null);
    for (const [fieldName, field] of fieldEntries) {
      positional[field.index - 1] = Object.prototype.hasOwnProperty.call(record, fieldName)
        ? record[fieldName]
        : field.default;
    }
    lines.push(`  [${id}] = {${positional.map(luaValue).join(",")}},`);
  }

  lines.push("}");
  return lines.join("\n");
}
