import { useState } from "react";

interface ExtractResult {
  fixes: string;
  sessionCount: number;
  fileCount: number;
  skippedFiles: { name: string; error: string }[];
}

interface EntitySection {
  key: "npc" | "quest" | "item" | "object";
  label: string;
  downloadName: string;
}

const SECTIONS: EntitySection[] = [
  { key: "npc", label: "NPC", downloadName: "foreverNpcTraces.lua" },
  { key: "quest", label: "Quest", downloadName: "foreverQuestTraces.lua" },
  { key: "item", label: "Item", downloadName: "foreverItemTraces.lua" },
  { key: "object", label: "Object", downloadName: "foreverObjectTraces.lua" },
];

type Status =
  | { kind: "idle" }
  | { kind: "loading"; entity?: EntitySection["key"] }
  | { kind: "done"; results: Record<EntitySection["key"], ExtractResult> }
  | { kind: "error"; message: string };

/**
 * "Extract" tab content: loads the forever*Traces.lua corrections modules
 * generated by tools/corrections-extractor (served via
 * /api/extract/{npc,quest,item,object}) and renders them for copy/download.
 *
 * Extraction itself runs in that separate CLI tool, because combining every
 * trace file in Traces/ doesn't fit in the dev server's memory.
 *
 * These are CORRECTIONS modules (only fields we actually have data for),
 * meant to be layered on top of Questie's base DB - not a full DB dump.
 */
export function ExtractView() {
  const [status, setStatus] = useState<Status>({ kind: "idle" });
  const [activeTab, setActiveTab] = useState<EntitySection["key"]>("npc");

  const handleLoadAll = () => {
    setStatus({ kind: "loading" });
    Promise.all(
      SECTIONS.map((section) =>
        fetch(`/api/extract/${section.key}`)
          .then((r) => r.json())
          .then((data: ExtractResult & { error?: string }) => {
            if (data.error) throw new Error(data.error);
            return [section.key, data] as const;
          }),
      ),
    )
      .then((entries) => {
        const results = Object.fromEntries(entries) as Record<EntitySection["key"], ExtractResult>;
        setStatus({ kind: "done", results });
      })
      .catch((e) => setStatus({ kind: "error", message: e.message }));
  };

  const handleLoadEntity = (entity: EntitySection["key"]) => {
    setStatus({ kind: "loading", entity });
    fetch(`/api/extract/${entity}`)
      .then((r) => r.json())
      .then((data: ExtractResult & { error?: string }) => {
        if (data.error) throw new Error(data.error);
        if (status.kind === "done") {
          setStatus({ kind: "done", results: { ...status.results, [entity]: data } });
        } else {
          const result = { [entity]: data } as Record<EntitySection["key"], ExtractResult>;
          // Fill in missing entities with placeholder data (so tabs all exist)
          for (const section of SECTIONS) {
            if (!(section.key in result)) {
              result[section.key] = { fixes: "", sessionCount: 0, fileCount: 0, skippedFiles: [] };
            }
          }
          setStatus({ kind: "done", results: result });
        }
      })
      .catch((e) => setStatus({ kind: "error", message: e.message }));
  };

  const handleCopy = (fixes: string) => {
    navigator.clipboard.writeText(fixes);
  };

  const handleDownload = (fixes: string, downloadName: string) => {
    const blob = new Blob([fixes], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = downloadName;
    a.click();
    URL.revokeObjectURL(url);
  };

  const isLoading = status.kind === "loading";
  const isDone = status.kind === "done";
  const activeResult = isDone ? status.results[activeTab] : null;
  const isLoadingEntity = status.kind === "loading" && status.entity !== undefined ? status.entity : null;
  const hasResults = isDone;

  return (
    <div className="extract-view">
      <div className="extract-toolbar">
        <button onClick={handleLoadAll} disabled={isLoading}>
          {isLoading && !status.entity ? "Loading all..." : "Load all"}
        </button>
      </div>

      {status.kind === "error" && <div className="error-msg">Error: {status.message}</div>}

      {hasResults && (
        <>
          <div className="extract-summary">
            {status.results.npc.sessionCount} session(s) from {status.results.npc.fileCount} trace file(s)
          </div>
          {status.results.npc.skippedFiles.length > 0 && (
            <div className="extract-warning">
              Skipped {status.results.npc.skippedFiles.length} file(s) that failed to load:
              <ul>
                {status.results.npc.skippedFiles.map((f) => (
                  <li key={f.name}>
                    {f.name}: {f.error}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}

      <div className="extract-tabs">
        <div className="extract-tab-list">
          {SECTIONS.map((section) => (
            <button
              key={section.key}
              className={`extract-tab ${activeTab === section.key ? "active" : ""}`}
              onClick={() => setActiveTab(section.key)}
            >
              {section.label}
            </button>
          ))}
        </div>

        <div className="extract-tab-content">
          {activeResult ? (
            <>
              <div className="extract-tab-header">
                <button
                  onClick={() => handleLoadEntity(activeTab)}
                  disabled={isLoadingEntity === activeTab}
                >
                  {isLoadingEntity === activeTab ? "Loading..." : "Reload"}
                </button>
                <button onClick={() => handleCopy(activeResult.fixes)} disabled={!activeResult.fixes}>
                  Copy to clipboard
                </button>
                <button
                  onClick={() => handleDownload(activeResult.fixes, SECTIONS.find((s) => s.key === activeTab)!.downloadName)}
                  disabled={!activeResult.fixes}
                >
                  Download
                </button>
              </div>
              <pre className="extract-output">{activeResult.fixes || "(No data for this entity)"}</pre>
            </>
          ) : (
            <>
              <div className="extract-tab-header">
                <button
                  onClick={() => handleLoadEntity(activeTab)}
                  disabled={isLoadingEntity === activeTab}
                >
                  {isLoadingEntity === activeTab ? "Loading..." : "Reload"}
                </button>
              </div>
              <div className="extract-tab-placeholder">
                <p>Run `npm run extract` in tools/corrections-extractor, then click "Load all".</p>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

