import { Component, useState, type ReactNode } from "react";

interface ExtractResult {
  fixes: string;
  sessionCount: number;
  fileCount: number;
  skippedFiles: { name: string; error: string }[];
}

/** relations-meta.json from `npm run relations -- combine` (combine/meta.ts in tools/corrections-extractor). */
interface RelationsMeta {
  generatedAt: string;
  minScore: number;
  episodeCount: number;
  characterCount: number;
  lua: { quests: number; relations: number };
  authored: { agree: number; new: number; conflict: number };
  caveat: string;
}

interface RelationsResult {
  fixes: string;
  meta: RelationsMeta;
  review: string;
}

const RERUN_COMBINE = "Run `npm run relations -- combine` in tools/corrections-extractor again.";

/** Every field the tab renders, so a meta file from an older or partial run can't break rendering. */
function isRelationsMeta(value: unknown): value is RelationsMeta {
  const meta = value as Partial<RelationsMeta> | null | undefined;
  const numbers = [
    meta?.minScore,
    meta?.episodeCount,
    meta?.characterCount,
    meta?.lua?.quests,
    meta?.lua?.relations,
    meta?.authored?.agree,
    meta?.authored?.new,
    meta?.authored?.conflict,
  ];
  return numbers.every((n) => typeof n === "number") && typeof meta?.generatedAt === "string" && typeof meta.caveat === "string";
}

interface EntitySection {
  key: "npc" | "quest" | "item" | "object";
  label: string;
  downloadName: string;
}

const SECTIONS: EntitySection[] = [
  { key: "npc", label: "NPC", downloadName: "foreverNpcTraces.lua" },
  { key: "quest", label: "Quest", downloadName: "foreverQuestTraces.lua" },
  { key: "item", label: "Item", downloadName: "foreverItemTraces.lua" },
  { key: "object", label: "Object", downloadName: "foreverObjectTraces.lua" },
];

type TabKey = EntitySection["key"] | "relations";

const TABS: { key: TabKey; label: string }[] = [...SECTIONS, { key: "relations", label: "Quest relations" }];

type Status =
  | { kind: "idle" }
  | { kind: "loading"; entity?: EntitySection["key"] }
  | { kind: "done"; results: Record<EntitySection["key"], ExtractResult> }
  | { kind: "error"; message: string };

type RelationsStatus =
  | { kind: "idle" }
  | { kind: "loading" }
  | { kind: "done"; result: RelationsResult }
  | { kind: "error"; message: string };

/** Fetches an /api/extract endpoint, turning its `{ error }` body into a rejection. */
function fetchExtract<T>(url: string): Promise<T> {
  return fetch(url)
    .then((r) => r.json())
    .then((data: T & { error?: string }) => {
      if (data.error) throw new Error(data.error);
      return data;
    });
}

function copyText(text: string) {
  navigator.clipboard.writeText(text);
}

function downloadText(text: string, fileName: string) {
  const blob = new Blob([text], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * "Extract" tab content: loads the forever*Traces.lua corrections modules
 * generated by tools/corrections-extractor (served via
 * /api/extract/{npc,quest,item,object}) and renders them for copy/download.
 * The "Quest relations" tab does the same for the relations pipeline's
 * module and review report (/api/extract/relations[/review]); it loads and
 * fails on its own, so a missing relations run never hides the four others.
 *
 * Extraction itself runs in that separate CLI tool, because combining every
 * trace file in Traces/ doesn't fit in the dev server's memory.
 *
 * These are CORRECTIONS modules (only fields we actually have data for),
 * meant to be layered on top of Questie's base DB - not a full DB dump.
 */
export function ExtractView() {
  const [status, setStatus] = useState<Status>({ kind: "idle" });
  const [relations, setRelations] = useState<RelationsStatus>({ kind: "idle" });
  const [activeTab, setActiveTab] = useState<TabKey>("npc");

  const handleLoadRelations = () => {
    setRelations({ kind: "loading" });
    Promise.all([
      fetchExtract<Omit<RelationsResult, "review">>("/api/extract/relations"),
      fetchExtract<{ review: string }>("/api/extract/relations/review"),
    ])
      .then(([module, { review }]) => {
        if (!isRelationsMeta(module.meta)) throw new Error(`relations-meta.json has an unexpected shape. ${RERUN_COMBINE}`);
        setRelations({ kind: "done", result: { ...module, review } });
      })
      .catch((e) => setRelations({ kind: "error", message: e.message }));
  };

  const handleLoadAll = () => {
    setStatus({ kind: "loading" });
    handleLoadRelations();
    Promise.all(
      SECTIONS.map((section) =>
        fetchExtract<ExtractResult>(`/api/extract/${section.key}`).then((data) => [section.key, data] as const),
      ),
    )
      .then((entries) => {
        const results = Object.fromEntries(entries) as Record<EntitySection["key"], ExtractResult>;
        setStatus({ kind: "done", results });
      })
      .catch((e) => setStatus({ kind: "error", message: e.message }));
  };

  const handleLoadEntity = (entity: EntitySection["key"]) => {
    setStatus({ kind: "loading", entity });
    fetchExtract<ExtractResult>(`/api/extract/${entity}`)
      .then((data) => {
        if (status.kind === "done") {
          setStatus({ kind: "done", results: { ...status.results, [entity]: data } });
        } else {
          const result = { [entity]: data } as Record<EntitySection["key"], ExtractResult>;
          // Fill in missing entities with placeholder data (so tabs all exist)
          for (const section of SECTIONS) {
            if (!(section.key in result)) {
              result[section.key] = { fixes: "", sessionCount: 0, fileCount: 0, skippedFiles: [] };
            }
          }
          setStatus({ kind: "done", results: result });
        }
      })
      .catch((e) => setStatus({ kind: "error", message: e.message }));
  };

  const isLoading = status.kind === "loading";
  const isDone = status.kind === "done";
  const activeResult = isDone && activeTab !== "relations" ? status.results[activeTab] : null;
  const isLoadingEntity = status.kind === "loading" && status.entity !== undefined ? status.entity : null;
  const hasResults = isDone;

  return (
    <div className="extract-view">
      <div className="extract-toolbar">
        <button onClick={handleLoadAll} disabled={isLoading}>
          {isLoading && !status.entity ? "Loading all..." : "Load all"}
        </button>
      </div>

      {status.kind === "error" && <div className="error-msg">Error: {status.message}</div>}

      {hasResults && (
        <>
          <div className="extract-summary">
            {status.results.npc.sessionCount} session(s) from {status.results.npc.fileCount} trace file(s)
          </div>
          {status.results.npc.skippedFiles.length > 0 && (
            <div className="extract-warning">
              Skipped {status.results.npc.skippedFiles.length} file(s) that failed to load:
              <ul>
                {status.results.npc.skippedFiles.map((f) => (
                  <li key={f.name}>
                    {f.name}: {f.error}
                  </li>
                ))}
              </ul>
            </div>
          )}
        </>
      )}

      <div className="extract-tabs">
        <div className="extract-tab-list">
          {TABS.map((tab) => (
            <button
              key={tab.key}
              className={`extract-tab ${activeTab === tab.key ? "active" : ""}`}
              onClick={() => setActiveTab(tab.key)}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="extract-tab-content">
          {activeTab === "relations" ? (
            <RelationsBoundary onReload={handleLoadRelations}>
              <RelationsTab status={relations} onReload={handleLoadRelations} />
            </RelationsBoundary>
          ) : activeResult ? (
            <>
              <div className="extract-tab-header">
                <button
                  onClick={() => handleLoadEntity(activeTab)}
                  disabled={isLoadingEntity === activeTab}
                >
                  {isLoadingEntity === activeTab ? "Loading..." : "Reload"}
                </button>
                <button onClick={() => copyText(activeResult.fixes)} disabled={!activeResult.fixes}>
                  Copy to clipboard
                </button>
                <button
                  onClick={() => downloadText(activeResult.fixes, SECTIONS.find((s) => s.key === activeTab)!.downloadName)}
                  disabled={!activeResult.fixes}
                >
                  Download
                </button>
              </div>
              <pre className="extract-output">{activeResult.fixes || "(No data for this entity)"}</pre>
            </>
          ) : (
            <>
              <div className="extract-tab-header">
                <button
                  onClick={() => handleLoadEntity(activeTab)}
                  disabled={isLoadingEntity === activeTab}
                >
                  {isLoadingEntity === activeTab ? "Loading..." : "Reload"}
                </button>
              </div>
              <div className="extract-tab-placeholder">
                <p>Run `npm run extract` in tools/corrections-extractor, then click "Load all".</p>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

/**
 * "Quest relations" tab: foreverQuestRelationTraces.lua with its run summary, or the review report
 * a person reads before trusting it. Copy and Download act on whichever of the two is shown.
 */
function RelationsTab({ status, onReload }: { status: RelationsStatus; onReload: () => void }) {
  const [showReview, setShowReview] = useState(false);

  const reload = (
    <button onClick={onReload} disabled={status.kind === "loading"}>
      {status.kind === "loading" ? "Loading..." : "Reload"}
    </button>
  );
  if (status.kind !== "done") {
    return (
      <>
        <div className="extract-tab-header">{reload}</div>
        {status.kind === "error" ? (
          <div className="error-msg">Error: {status.message}</div>
        ) : (
          <div className="extract-tab-placeholder">
            <p>Run `npm run relations -- pipeline` in tools/corrections-extractor, then click "Load all".</p>
          </div>
        )}
      </>
    );
  }

  const { fixes, meta, review } = status.result;
  const [text, fileName] = showReview ? [review, "relations-review.md"] : [fixes, "foreverQuestRelationTraces.lua"];
  return (
    <>
      <div className="extract-tab-header">
        {reload}
        <button onClick={() => setShowReview(!showReview)}>{showReview ? "Show Lua module" : "Show review report"}</button>
        <button onClick={() => copyText(text)}>Copy to clipboard</button>
        <button onClick={() => downloadText(text, fileName)}>Download</button>
      </div>
      <div className="extract-summary">
        {meta.lua.quests} Forever quest(s), {meta.lua.relations} relation(s) from {meta.episodeCount} episode(s) of{" "}
        {meta.characterCount} character(s); min score {meta.minScore}; authored quests: {meta.authored.agree} agree,{" "}
        {meta.authored.new} new, {meta.authored.conflict} conflict. Generated {meta.generatedAt}.
      </div>
      <div className="extract-warning">{meta.caveat}</div>
      <pre className={showReview ? "extract-output extract-review" : "extract-output"}>{text}</pre>
    </>
  );
}

/**
 * Keeps a render error in the relations tab inside that tab: without it React unmounts the whole
 * app, the four field tabs included. Reload clears the error and fetches again.
 */
class RelationsBoundary extends Component<{ onReload: () => void; children: ReactNode }, { error: Error | null }> {
  state: { error: Error | null } = { error: null };

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  render() {
    if (!this.state.error) return this.props.children;
    return (
      <>
        <div className="extract-tab-header">
          <button
            onClick={() => {
              this.setState({ error: null });
              this.props.onReload();
            }}
          >
            Reload
          </button>
        </div>
        <div className="error-msg">
          Error: the quest relations could not be shown ({this.state.error.message}). {RERUN_COMBINE}
        </div>
      </>
    );
  }
}
