name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  tests:
    uses: './.github/workflows/ci.yml'
    with:
      event_name: ${{ github.event_name }}
      repo_full_name: ${{ github.repository }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  publish:
    runs-on: ubuntu-latest
    needs: [tests]

    env:
      GH_TOKEN: ${{ github.token }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      RELEASE_TAG: ${{ github.ref_name }}

    steps:
      - name: Clone project
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          fetch-depth: 100

      - name: Fetch tags
        run: git fetch --prune --unshallow --tags

      - name: Generate Changelog
        uses: orhun/git-cliff-action@3d96a18cc4ec17e9dc69ddcc424ccafaf1f78ce2 # v4.9.0
        with:
          config: cliff.toml
          args: --latest --strip header
        id: cliff
        env:
          OUTPUT: CHANGELOG.md

      - name: Ensure Changelog File
        run: |
          if [ ! -f CHANGELOG.md ]; then
            echo "${{ steps.cliff.outputs.content }}" > CHANGELOG.md
          fi
          echo "Changelog content saved to CHANGELOG.md"

      - name: Build ZIP
        run: python build.py -r

      - name: Create GitHub release
        run: |
          if [[ "$RELEASE_TAG" == *"-b"* ]]; then
            gh release create "$RELEASE_TAG" \
              --verify-tag \
              --prerelease \
              -F CHANGELOG.md \
              "releases/$RELEASE_TAG/QuestieTrace-$RELEASE_TAG.zip" \
              "releases/$RELEASE_TAG/release.json"
          else
            gh release create "$RELEASE_TAG" \
              --verify-tag \
              -F CHANGELOG.md \
              "releases/$RELEASE_TAG/QuestieTrace-$RELEASE_TAG.zip" \
              "releases/$RELEASE_TAG/release.json"
          fi

      - name: Upload CurseForge
        run: sh upload-cf.sh "$RELEASE_TAG"
